version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "yearly"
    labels: ["dependencies"]
    open-pull-requests-limit: 5
    reviewers: ["khluu"]
    versioning-strategy: "auto"
    allow:
      - dependency-type: "all"
    groups:
      a:
        applies-to: version-updates
        update-types: "minor"
